#!/usr/bin/env python3
"""Experiment I of DESIGN.md: the 2x2 (constraint x self-energy) on Au(111) + TIP4P-FQ water, scanned in eta_Au.

Writes runs/exp1/<arm>_eta<eta>/{in.lammps,param} (+ lmin/ for the Lanczos run) and runs them, 8 at a time,
one rank each, on the release binary. Re-running skips finished runs. Analysis: analyze_exp1.py.
"""
import os, subprocess, sys
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path

HERE = Path(__file__).resolve().parent
LMP = os.environ.get("LMP", str(Path.home() / "codes/lammps/lammps-release/build/lmp"))
ETAS = ["5.172", "2.5", "1.0", "0.3", "0.05"]
ARMS = {  # name: (constraint, self-energy)
    "qeq":        ("global", False),
    "qeq_gself":  ("global", True),
    "mol":        ("mol",    False),
    "samqeq":     ("mol",    True),
}

PARAM = """0.30  10.0  2.0  3.5  0.0  2
1  5.3100  {eta}  1.6180  0.0  -7.0  3.0
2  0.00  100.00  0.315328  0.0  -7.0  3.0
3  4.50   15.31  0.404355  0.0  -7.0  3.0
4  7.47   16.11  0.315328  0.0  -7.0  3.0
"""

DECK = """# conductor demonstration, experiment I: arm {arm}, eta_Au {eta} eV (generated by run_exp1.py)
units           metal
atom_style      full
boundary        p p f
read_data       ../../../data.exp1
group           au   type 1
group           watO type 2
group           fq   type 1 3 4
{nometal}
pair_style      hybrid/overlay lj/cut 12.0 coul/long 12.0 coul/shield/intra 12.0 all gaussian
pair_coeff      * * lj/cut 0.0 1.0
pair_coeff      2 2 lj/cut 0.012412 3.159
pair_coeff      * * coul/long
pair_coeff      1 1 coul/shield/intra 1.618000
pair_coeff      1 2 coul/shield/intra 0.714283
pair_coeff      1 3 coul/shield/intra 0.808855
pair_coeff      1 4 coul/shield/intra 0.714283
pair_coeff      2 2 coul/shield/intra 0.315328
pair_coeff      2 3 coul/shield/intra 0.357078
pair_coeff      2 4 coul/shield/intra 0.315328
pair_coeff      3 3 coul/shield/intra 0.404355
pair_coeff      3 4 coul/shield/intra 0.357078
pair_coeff      4 4 coul/shield/intra 0.315328
special_bonds   lj/coul 1.0e-8 1.0e-8 1.0
kspace_style    pppm/samqeq 1.0e-6
kspace_modify   slab 3.0 mesh 24 28 80 gewald 0.35
neighbor        2.0 bin
{cons}
fix             chg fq qeq/sam 1 0.0 10.0 1.0e-8 param
fix_modify      chg shield gaussian
fix_modify      chg energy yes
{gself}
{lmin}
run             0
write_dump      all custom charges.dump id mol type q x y z modify sort id format line "%d %d %d %.12g %.8f %.8f %.8f"
variable        peval equal pe
print           "${{peval}}" file pe.txt screen no
"""


def make(arm, eta, lmin=False, nometal=False):
    cons, gs = ARMS[arm]
    name = f"{arm}_eta{eta}" + ("_nometal" if nometal else "")
    d = HERE / "runs/exp1" / name / ("lmin" if lmin else "")
    d.mkdir(parents=True, exist_ok=True)
    (d / "param").write_text(PARAM.format(eta=eta))
    deck = DECK.format(
        arm=arm, eta=eta,
        nometal="delete_atoms    group au bond yes\n" if nometal else "",
        cons="set             group all mol 1   # ONE global neutrality constraint" if cons == "global" else
             "# per-molecule neutrality: each water is its own fragment, the slab is one fragment",
        gself="fix_modify      chg gself on width 0.50 types 1" if gs else "",
        lmin="fix_modify      chg ridge eig 1000.0 200   # diagnostic: prints the Lanczos lambda_min" if lmin else "")
    deck = deck.replace("../../../data.exp1", str(HERE / "data.exp1"))
    (d / "in.lammps").write_text(deck)
    return d


def run(d):
    if (d / "pe.txt").exists():
        return d, 0
    r = subprocess.run([LMP, "-in", "in.lammps", "-log", "log.lammps", "-screen", "none"], cwd=d,
                       capture_output=True, text=True)
    (d / "run.out").write_text(r.stdout + r.stderr)
    return d, r.returncode


if __name__ == "__main__":
    dirs = []
    for arm in ARMS:
        for eta in ETAS:
            dirs.append(make(arm, eta)); dirs.append(make(arm, eta, lmin=True))
    dirs.append(make("samqeq", "5.172", nometal=True))   # the same film with no metal (molecular reference)
    with ThreadPoolExecutor(int(os.environ.get("NJ", "8"))) as ex:
        for d, rc in ex.map(run, dirs):
            if rc: print(f"FAIL rc={rc} {d.relative_to(HERE)}")
    print("done", len(dirs))
